// Generated by the llm-connect skill. Environment variables override the defaults at runtime.
export const LLM_CONFIG = {
  route: '/api/chat',
  defaultEngine: 'anthropic',
  anthropicModel: 'claude-sonnet-5',
  ollamaModel: 'phi3',
  ollamaBaseUrl: 'http://127.0.0.1:11434',
  /** Most characters of history sent per call; older turns are dropped first. */
  historyChars: 24000,
  maxOutputTokens: 1024,
  /** The server gives up when the engine sends nothing for this long. */
  idleTimeoutMs: 20_000,
  maxRequestBytes: 256_000,
} as const;
