// Generated by the llm-connect skill. Environment variables override the defaults at runtime.
import { MAX_HISTORY_CHARS } from '../../src/shared/llm/limits.ts';

export const LLM_CONFIG = {
  route: '/api/chat',
  /** GET: the active engine and whether it can run to-do actions (ADR-11). */
  engineRoute: '/api/engine',
  defaultEngine: 'anthropic',
  anthropicModel: 'claude-sonnet-5',
  ollamaModel: 'phi3',
  ollamaBaseUrl: 'http://127.0.0.1:11434',
  /** Most characters of history sent per call; older turns are dropped first. */
  historyChars: MAX_HISTORY_CHARS,
  maxOutputTokens: 1024,
  /** The server gives up when the engine sends nothing for this long. */
  idleTimeoutMs: 20_000,
  maxRequestBytes: 256_000,
} as const;
