// Generated by the llm-connect skill. Checks the chat endpoint end to end through Vite's own
// server: streaming, history, every failure mode it can trigger safely, and no secrets in the
// production bundle. Usage: npm run verify:llm   (exits non-zero if any check fails)
import { mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { build, createServer, loadEnv } from 'vite';

const ROUTE = '/api/chat';
const ENV_KEYS = [
  'INFERENCE_ENGINE',
  'ANTHROPIC_API_KEY',
  'ANTHROPIC_MODEL',
  'OLLAMA_BASE_URL',
  'OLLAMA_MODEL',
  'MOCK_DELAY_MS',
];
const results = [];
const check = (id, criterion, pass, detail) =>
  results.push({ id, criterion, pass: Boolean(pass), detail });

// The plugin reads process.env over .env, so each scenario sets exactly what it needs.
async function withServer(env, run) {
  const saved = Object.fromEntries(ENV_KEYS.map((key) => [key, process.env[key]]));
  for (const key of ENV_KEYS) {
    if (key in env) {
      if (env[key] === undefined) delete process.env[key];
      else process.env[key] = env[key];
    }
  }
  const server = await createServer({
    logLevel: 'silent',
    server: { port: 5320, strictPort: false, hmr: false },
  });
  try {
    await server.listen();
    const base = server.resolvedUrls?.local[0];
    if (!base) throw new Error('Vite did not report a local URL');
    return await run(new URL(ROUTE, base).href);
  } finally {
    await server.close();
    for (const [key, value] of Object.entries(saved)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
  }
}

async function chat(url, body) {
  const started = performance.now();
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: typeof body === 'string' ? body : JSON.stringify(body),
  });
  const events = [];
  let firstDeltaMs = null;
  let buffer = '';
  const decoder = new TextDecoder();
  for await (const chunk of response.body) {
    buffer += decoder.decode(chunk, { stream: true });
    let newline;
    while ((newline = buffer.indexOf('\n')) >= 0) {
      const line = buffer.slice(0, newline);
      buffer = buffer.slice(newline + 1);
      if (!line.trim()) continue;
      const event = JSON.parse(line);
      if (event.type === 'delta' && firstDeltaMs === null)
        firstDeltaMs = performance.now() - started;
      events.push(event);
    }
  }
  const text = events
    .filter((e) => e.type === 'delta')
    .map((e) => e.text)
    .join('');
  return {
    status: response.status,
    type: response.headers.get('content-type'),
    events,
    text,
    firstDeltaMs,
    last: events.at(-1),
  };
}

const user = (content) => ({ role: 'user', content });
const errorCode = (reply) =>
  reply.last?.type === 'error' ? reply.last.error.code : reply.last?.type;
const fileEnv = loadEnv('production', process.cwd(), '');
const liveKey = (process.env.ANTHROPIC_API_KEY ?? fileEnv.ANTHROPIC_API_KEY ?? '').trim();

try {
  await withServer({ INFERENCE_ENGINE: 'mock', MOCK_DELAY_MS: '5' }, async (url) => {
    const reply = await chat(url, {
      messages: [
        user('My name is Ada.'),
        { role: 'assistant', content: 'Hi Ada!' },
        user('What is my name?'),
      ],
    });
    check(
      'stream',
      'Streams NDJSON: start, several deltas, done',
      reply.type?.includes('application/x-ndjson') &&
        reply.events[0]?.type === 'start' &&
        reply.events.filter((e) => e.type === 'delta').length > 3 &&
        reply.last?.type === 'done',
      `${String(reply.events.length)} events, last: ${reply.last?.type}`,
    );
    check(
      'history',
      'The whole history reaches the engine',
      reply.text.includes('received 2 of your messages'),
      reply.text.slice(-70),
    );

    const injected = await chat(url, { messages: [user('Hello [mock:rate_limit]')] });
    check(
      'api-error',
      'Provider errors arrive as typed error events',
      errorCode(injected) === 'rate_limit' && injected.last.error.retryable === true,
      JSON.stringify(injected.last),
    );

    const malformed = await chat(url, 'not json');
    check(
      'bad-request',
      'A malformed request gets a bad_request error, not a crash',
      errorCode(malformed) === 'bad_request',
      JSON.stringify(malformed.last),
    );

    const get = await fetch(url);
    check('method', 'Only POST is accepted', get.status === 405, `GET → ${String(get.status)}`);
  });

  await withServer(
    { INFERENCE_ENGINE: 'ollama', OLLAMA_BASE_URL: 'http://127.0.0.1:9' },
    async (url) => {
      const reply = await chat(url, { messages: [user('Hi')] });
      check(
        'unreachable',
        'An unreachable engine gives engine_unreachable',
        errorCode(reply) === 'engine_unreachable',
        JSON.stringify(reply.last),
      );
    },
  );

  await withServer({ INFERENCE_ENGINE: 'anthropic', ANTHROPIC_API_KEY: '' }, async (url) => {
    const reply = await chat(url, { messages: [user('Hi')] });
    check(
      'config',
      'A missing key gives a config error',
      errorCode(reply) === 'config',
      JSON.stringify(reply.last),
    );
  });

  await withServer(
    { INFERENCE_ENGINE: 'anthropic', ANTHROPIC_API_KEY: 'sk-ant-invalid-key-for-verify' },
    async (url) => {
      const reply = await chat(url, { messages: [user('Hi')] });
      check(
        'auth',
        'An invalid Anthropic key gives auth (real API call)',
        errorCode(reply) === 'auth',
        JSON.stringify(reply.last).slice(0, 200),
      );
    },
  );

  if (liveKey) {
    await withServer(
      { INFERENCE_ENGINE: 'anthropic', ANTHROPIC_API_KEY: undefined },
      async (url) => {
        const reply = await chat(url, {
          messages: [
            user('My favourite colour is teal. Reply with one short sentence.'),
            { role: 'assistant', content: 'Teal is a lovely colour!' },
            user('What is my favourite colour? Answer with one word.'),
          ],
        });
        check(
          'live',
          'Claude answers through the endpoint, using the history',
          reply.last?.type === 'done' && /teal/i.test(reply.text),
          `${reply.text.trim().slice(0, 80)} (first text after ${String(Math.round(reply.firstDeltaMs ?? -1))} ms)`,
        );
      },
    );
  } else {
    check(
      'live',
      'Claude answers through the endpoint, using the history',
      true,
      'skipped: no ANTHROPIC_API_KEY in .env',
    );
  }

  const outDir = mkdtempSync(join(tmpdir(), 'verify-llm-build-'));
  try {
    await build({ logLevel: 'silent', build: { outDir, emptyOutDir: true } });
    const needles = ['ANTHROPIC_API_KEY', 'sk-ant-', ...(liveKey ? [liveKey] : [])];
    const leaks = [];
    const walk = (dir) => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const path = join(dir, entry.name);
        if (entry.isDirectory()) walk(path);
        else {
          const content = readFileSync(path, 'utf8');
          for (const needle of needles)
            if (content.includes(needle))
              leaks.push(`${entry.name} contains ${needle === liveKey ? 'the real key' : needle}`);
        }
      }
    };
    walk(outDir);
    check(
      'secrets',
      'No key name or value in the production bundle',
      leaks.length === 0,
      leaks.join('; ') || 'clean',
    );
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
} catch (error) {
  check(
    'script',
    'Verification completed',
    false,
    error instanceof Error ? (error.stack ?? error.message) : String(error),
  );
}

console.log(JSON.stringify({ results }, null, 2));
process.exitCode = results.every((r) => r.pass) ? 0 : 1;
